---
- hosts: all
  become: yes
  vars_files:
    - global_vars.yaml
  pre_tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: no
  roles:
    - { role: docker, when: execute_docker_role }
    - { role: swarm, when: execute_swarm_role }
    - { role: traefik, when: execute_traefik_role }
    - { role: portainer, when: execute_portainer_role }
