---
- name: Criar namespace para o Longhorn
  kubernetes.core.k8s:
    kind: Namespace
    name: longhorn-system
    state: present

- name: Adicionar repositório Helm do Longhorn
  kubernetes.core.helm_repository:
    name: longhorn-stable
    repo_url: https://charts.longhorn.io

- name: Instalar/Atualizar Longhorn
  kubernetes.core.helm:
    name: longhorn
    namespace: longhorn-system
    chart_ref: longhorn-stable/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    state: present
    wait: true
    values:
      ingress:
        enabled: false

- name: Aplicar Ingress para o Longhorn
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'longhorn-ingress.yaml.j2') | from_yaml }}"

- name: Aplicar Certificate para o Longhorn
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'longhorn-certificate.yaml.j2') | from_yaml }}"
