- name: Gerar arquivo de configuração do pgadmin a partir do template
  template:
    src: "pgadmin.yaml.j2"
    dest: "/tmp/pgadmin.yaml"

- name: Ensure pgadmin stack is deployed
  docker_stack:
    state: present
    name: pgadmin
    compose:
      - "/tmp/pgadmin.yaml"
    prune: yes
    resolve_image: always