- name: Gerar arquivo de configuração do n8n a partir do template
  template:
    src: "n8n-queue.yaml.j2"
    dest: "/tmp/n8n-queue.yaml"

- name: Ensure n8n stack is deployed
  docker_stack:
    state: present
    name: n8n
    compose:
      - "/tmp/n8n-queue.yaml"
    prune: yes
    resolve_image: always