- name: Gerar arquivo de configuração do portainer a partir do template
  template:
    src: "portainer.yaml.j2"
    dest: "/tmp/portainer.yaml"

- name: Ensure portainer stack is deployed
  docker_stack:
    state: present
    name: portainer
    compose:
      - "/tmp/portainer.yaml"
    prune: yes
    resolve_image: always