- name: Gerar arquivo de configuração do Traefik a partir do template
  template:
    src: "traefik.yaml.j2"
    dest: "/tmp/traefik.yaml"

- name: Ensure Traefik stack is deployed
  docker_stack:
    state: present
    name: traefik
    compose:
      - "/tmp/traefik.yaml"
    prune: yes
    resolve_image: always
